[symlinks]
"bash/.bashrc" = "/home/cboyce/.bashrc"
"fish/config.fish" = "/home/cboyce/.config/fish/config.fish"
"helix/config.toml" = "/home/cboyce/.config/helix/config.toml"
"nushell/config.nu" = "/home/cboyce/.config/nushell/config.nu"
"starship/init.nu" = "/home/cboyce/.cache/starship/init.nu"
"starship/starship.toml" = "/home/cboyce/.config/starship.toml"
"zellij/config.kdl" = "/home/cboyce/.config/zellij/config.kdl"

[templates]
