[helpers]

[xplr.files]
"xplr/init.lua" = "~/.config/xplr/init.lua"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"

[nushell.files]
"nushell/config.nu" = "~/.config/nushell/config.nu"

[bash.files]
"bash/.bashrc" ="~/.bashrc"

[starship.files]
"starship/starship.toml" ="~/.config/starship.toml"
"starship/init.nu" = "~/.cache/starship/init.nu"

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"

[default]
depends = ["bash","helix","zellij","nushell","starship","fish","xplr"]

[default.files]
helix = ""

[default.variables]
