[helpers]

[nushell.files]
"nushell/config.nu" = "~/.config/nushell/config.nu"

[bash.files]
"bash/.bashrc" ="~/.bashrc"

[starship.files]
"starship/config.toml" ="~/.config/starship.toml"

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"

[default]
depends = ["helix","zellij","nushell"]

[default.files]
helix = ""

[default.variables]
